#!/usr/bin/env ruby
#^syntax detection

#role "tulibraries.ansible-rails_app",
#      git: "git@github.com:tulibraries/ansible-rails_app"

role "geerlingguy.apache",
      git: "git@github.com:geerlingguy/ansible-role-apache"

#role "tulibraries.ansible_passenger-apache",
#      git: "git@github.com:tulibraries/ansible_passenger-apache"

role "zzet.rbenv",
      git: "git@github.com:zzet/ansible-rbenv-role"

role "geerlingguy.solr",
      git: "git@github.com:geerlingguy/ansible-role-solr"

# more roles can be added here, you can pull them from GitHub or from Ansible Galaxy
# docs here: https://github.com/bcoe/librarian-ansible
