#!/usr/bin/env ruby
#^syntax detection

role "uclalibrary.uclalib_role_epel",
      git: "git@github.com:UCLALibrary/uclalib_role_epel"

role "uclalibrary.uclalib_role_java",
      git: "git@github.com:UCLALibrary/uclalib_role_java"

role "uclalibrary.uclalib_role_apache",
      git: "git@github.com:UCLALibrary/uclalib_role_apache"

role "uclalibrary.uclalib_role_solr7",
      git: "git@github.com:UCLALibrary/uclalib_role_solr7"

# more roles can be added here, you can pull them from GitHub or from Ansible Galaxy
# docs here: https://github.com/bcoe/librarian-ansible
