# this playbook is used to construct our base box

# Additional playbook wide variables can be found in
# group_vars/all/vars.yml
# Encrypted vars, like passwords, can be found in
# group_vars/all/pw.yml


- name: embark-basebox.yml
  become: yes
  become_method: sudo
  hosts: all
  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: ansible-packages }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_mysql, mysql_install_version: '5.6' }
    - { role: uclalib_role_java, oracle_java_version: '1.8.0_181' }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_solr7, solr_version: '7.4.0' }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_fedora4, fedora_version: '4.7.5' }
    - { role: uclalib_role_samvera_basepackages }
    - { role: uclalib_role_pip }
    - { role: uclalib_role_imagemagick }
    - { role: uclalib_role_libreoffice, libreoffice_version: '6.0.6' }
    - { role: uclalib_role_ffmpeg, ffmpeg_version: '4.0.2' }
    - { role: uclalib_role_fits, fits_version: '1.3.0' }
    - { role: uclalib_role_ruby, ruby_version: '2.5.1' }
    - { role: uclalib_role_passenger, passenger_version: '5.3.3' }
    - { role: uclalib_role_nodejs, nodejs_version: '8' }
    - { role: uclalib_role_yarn }
    - { role: uclalib_role_redis }
